Repository cryptic-game/java-lib, pull requests merged in 2019-10, with the labels that each got.

#19 Added JSONObjectDecoder to the channel pipeline (#18)
  src/main/java/net/cryptic_game/microservice/MicroServiceInitializer.java
Labels: bug

#21 Added Exception capturing with Sentry
  pom.xml
  src/main/java/net/cryptic_game/microservice/MicroService.java
  src/main/java/net/cryptic_game/microservice/config/DefaultConfig.java
  src/main/java/net/cryptic_game/microservice/db/Database.java
Labels: enhancement

#23 Issues/22 sleep bewteen reconnect to server
  pom.xml
  src/main/java/net/cryptic_game/microservice/MicroService.java
Labels: dependencies, enhancement

#25 Issue/24 compare users
  src/main/java/net/cryptic_game/microservice/wrapper/User.java
Labels: enhancement
